# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0002_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='likes',
            field=models.ManyToManyField(related_name='user_likers', to='secrets.User'),
        ),
    ]
